/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import AnalizadorLexico.LeerArchivo;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author felip
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    public InterfazPrincipal() {
        initComponents();
        setLocationRelativeTo(null);

        setIconImage(
                new ImageIcon(getClass().getResource("/Imagenes/icono.png")).getImage()
        );

        String noFilas = "<html>";
        for (int i = 1; i < 500; i++) {
            noFilas = noFilas + i + "<br>";
        }
        noFilas = noFilas + "</html>";
        filas.setText(noFilas);

        String textoLeido = "";
        String[] textoLeido2 = new String[7];

        LeerArchivo leerArchivo = new LeerArchivo();
        textoLeido2 = leerArchivo.leerTextoConScanner();
        
        for (int i = 0; i < textoLeido2.length; i++) {
            textoLeido = textoLeido + textoLeido2[i];
            
        }

        txtAreaArchivoLeido.setEnabled(false);
        txtAreaArchivoLeido.setText(textoLeido);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnAbrir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEditar1 = new javax.swing.JButton();
        btnEditar2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        filas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaArchivoLeido = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analizador Léxico");
        setMaximumSize(new java.awt.Dimension(900, 849));
        setMinimumSize(new java.awt.Dimension(900, 849));
        setPreferredSize(new java.awt.Dimension(900, 849));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        btnAbrir.setBackground(new java.awt.Color(204, 255, 255));
        btnAbrir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAbrir.setForeground(new java.awt.Color(0, 0, 0));
        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-abrir-carpeta-48.png"))); // NOI18N
        btnAbrir.setText("Abrir");
        btnAbrir.setFocusPainted(false);
        btnAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAbrirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAbrirMouseExited(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(204, 255, 255));
        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(0, 0, 0));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoEditar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setFocusPainted(false);
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnEditar1.setBackground(new java.awt.Color(204, 255, 255));
        btnEditar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditar1.setForeground(new java.awt.Color(0, 0, 0));
        btnEditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoAnalizar.png"))); // NOI18N
        btnEditar1.setText("analizar");
        btnEditar1.setFocusPainted(false);
        btnEditar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditar1MouseExited(evt);
            }
        });
        btnEditar1.addActionListener(this::btnEditar1ActionPerformed);

        btnEditar2.setBackground(new java.awt.Color(204, 255, 255));
        btnEditar2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditar2.setForeground(new java.awt.Color(0, 0, 0));
        btnEditar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoGuardar.png"))); // NOI18N
        btnEditar2.setText("Guardar");
        btnEditar2.setFocusPainted(false);
        btnEditar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditar2MouseExited(evt);
            }
        });
        btnEditar2.addActionListener(this::btnEditar2ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnAbrir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar2)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbrir)
                    .addComponent(btnEditar)
                    .addComponent(btnEditar1)
                    .addComponent(btnEditar2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        filas.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        filas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        filas.setText("0");
        filas.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(filas, java.awt.BorderLayout.LINE_START);

        txtAreaArchivoLeido.setColumns(20);
        txtAreaArchivoLeido.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtAreaArchivoLeido.setRows(5);
        jScrollPane1.setViewportView(txtAreaArchivoLeido);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirMouseEntered
        btnAbrir.setBackground(Color.yellow);
    }//GEN-LAST:event_btnAbrirMouseEntered

    private void btnAbrirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirMouseExited
        btnAbrir.setBackground(new Color(204, 255, 255));
    }//GEN-LAST:event_btnAbrirMouseExited

    private void btnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarMouseEntered

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarMouseExited

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        txtAreaArchivoLeido.setEnabled(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEditar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar1MouseEntered

    private void btnEditar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar1MouseExited

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void btnEditar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditar2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar2MouseEntered

    private void btnEditar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditar2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar2MouseExited

    private void btnEditar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnEditar2;
    private javax.swing.JLabel filas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAreaArchivoLeido;
    // End of variables declaration//GEN-END:variables
}
